lib/services/generator/math_util.dart, lib/services/generator/trajectory.dart, pathplannerlib/src/main/java/com/pathplanner/lib/PathPlannerTrajectory.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlannerTrajectory.cpp
* Use MathUtil.inputModulus from WPILibJ
* Use frc::InputModulus from WPILibC
* Add a MathUtil.inputModulus for the Dart version
* Add rotation limiting to the angular velocities, keeping them from
being inaccurate at +/- 180 degrees crossings.
=> Better handling of rotation in trajectories

lib/services/generator/geometry_util.dart, lib/services/generator/trajectory.dart
The Dart implementation of Trajectory uses a linear interpolation for rotation, which does not respect the rotational symmetry. This replaces the linear interpolation of rotation with a rotational interpolation (equivalent to what happens in the C++ and Java version).
This is the reason that the robot in the GUI (on the Preview editor) sometimes "twitches" when it crosses the +/- 180 degree boundary, which no longer happens now.
=> Add rotationLerp for interpolation of rotation

lib/robot_path/robot_path.dart
Using a human-readable format for the JSON path output has two advantages:
1. It makes it much easier for a version control system to track and highlight what has changed in a path.
2. It makes it easier to hand-edit the path (for precise control-point locations...if you're a bit AR like myself).
=> Save paths in human-readable format.

pathplannerlib/src/main/java/com/pathplanner/lib/PathPlanner.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlanner.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/PathPlanner.h
This PR changes the generatePath method to accept a list of PathPoints instead of taking two arguments and a vararg of PathPoints.
The reasoning behind this change is situations like my own, where I would like to be able to pass several points into a function to get a command that runs a path.  Using the PathPlanner generatePath method everywhere would mean unnecessary code duplication of the constraints (I'm only running one robot, the constraints don't change during runtime).  This causes me to have to write ugly code in order to accept a list of points, getting the first two by index and then calling subList and converting that sub list to an array.
The secondary reasoning is that the paths are simply reconstructed into an ArrayList at the end of the day already.  It doesn't make sense …
=> Use list of points instead of vararg for specifying on the fly trajectories.

pathplannerlib/src/main/java/com/pathplanner/lib/auto/BaseAutoBuilder.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/BaseAutoBuilder.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/auto/BaseAutoBuilder.h
Closes #176 
Closes #181 
* If stopEvent.names is empty, just return a wait command
* Removed reliance on `CommandGroupBase`, opting for the newer `Commands` API
* Created a utility `CommandList` class. It is just a subclass of `ArrayList<CommandBase>` with some helpful methods to make converting between collections of Commands to arrays of commands a lot prettier and easier. Let me know your thoughts on this, but to me it seems like the most elegant solution
* Heavy reliance on the java stream api
Let me know if you like these changes, and I can work on the C++ implementation.
=> Updated pplib to use new Commands API

lib/pages/home_page.dart, pathplannerlib/.vscode/settings.json, pathplannerlib/publish.gradle, pathplannerlib/src/main/java/com/pathplanner/lib/PathPlanner.java, pathplannerlib/src/main/java/com/pathplanner/lib/PathPlannerTrajectory.java, pathplannerlib/src/main/java/com/pathplanner/lib/commands/PPMecanumControllerCommand.java, pathplannerlib/src/main/java/com/pathplanner/lib/commands/PPRamseteCommand.java, pathplannerlib/src/main/java/com/pathplanner/lib/commands/PPSwerveControllerCommand.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlanner.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlannerTrajectory.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/PPMecanumControllerCommand.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/PPSwerveControllerCommand.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/PathPlannerTrajectory.h, pathplannerlib/src/main/native/include/pathplanner/lib/commands/PPMecanumControllerCommand.h, pathplannerlib/src/main/native/include/pathplanner/lib/commands/PPSwerveControllerCommand.h
PPLib path following commands will automatically transform path states for the current alliance color. In order for this to work properly, paths created in the GUI MUST be made on the blue side of the field.
This will not transform any states if the path was generated on-the-fly since those should be made in the correct coordinate system already.
If not using PPLib commands, you will need to use the transformStateForAlliance method manually to transform the path states.
=> Transform path states based on alliance color

pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/BaseAutoBuilder.cpp
Add initialization of drivetrain type to `BaseAutoBuilder` that a lack of had previously created issues for differential drive paths starting at non zero rotations
=> Fix drivetrain type initialization

lib/pages/home_page.dart, lib/widgets/dialogs/settings_dialog.dart, lib/widgets/path_editor/cards/waypoint_card.dart, lib/widgets/path_editor/editors/edit_editor.dart, lib/widgets/path_editor/path_editor.dart, lib/widgets/path_editor/path_painter_util.dart
Closes #245 
Closes #248 
Adds an option to hide all waypoints that aren't directly connected to the selected waypoint. I still think there is work to be done here, and would appreciate feedback from others to make this as nice a feature as possible.
=> Add Focused Selection Option

pathplannerlib/src/main/java/com/pathplanner/lib/PathPoint.java
One great feature of WPILib's `Pose2d` is the ability to [equality-check](https://github.com/wpilibsuite/allwpilib/blob/aa34aacf6eff05477400bbcc46a2e9e4014e0059/wpimath/src/main/java/edu/wpi/first/math/geometry/Pose2d.java#L272-L279
) the objects.
I've ported the logic for PathPoints.
=> Add equality checking for PathPoints

.github/workflows/publish-javadoc.yml
As pitched in https://github.com/mjansen4857/pathplanner/pull/310
The GitHub Actions workflow is triggered based on a release (does not include drafts, or pre-release). Once a release is published (either directly, from a draft, or from a pre-release), it will assume that it's the latest version of PathPlannerLib.
It will build PathPlannerLib, and push the Javadoc directory to the `gh-pages` branch. It is not necessary to create a new branch for each version, because GitHub Pages can only host one version, and the generated Javadocs do not have versions built in. It will always be the latest version.
You can see a demo in my fork on the repo, at https://github.com/jasonli0616/pathplanner and https://jasonli0616.github.io/pathplanner/docs/java/
Because the workflow must push to the repo, …
=> Create a GitHub Actions workflow to publish generated Javadoc to GitHub Pages

pathplannerlib/build.gradle
A continuation of https://github.com/mjansen4857/pathplanner/pull/313, one last thing:
This should now link the Java docs and WPILib docs in the PathPlanner docs, where it's referenced.
=> Link Javadoc to external sources (Java API, WPILib API)

pathplannerlib/build.gradle, pathplannerlib/src/main/java/com/pathplanner/lib/path/PathPlannerTrajectory.java, pathplannerlib/src/main/native/include/pathplanner/lib/path/PathPlannerTrajectory.h, pathplannerlib/src/test/java/com/pathplanner/lib/path/PathPlannerTrajectoryTest.java, pathplannerlib/src/test/native/cpp/pathplanner/lib/path/PathPlannerTrajectoryTest.cpp
The reverse function in PathPlannerTrajectory was not including all of the fields in either language, so if a DiffDrive path was reversed it would always try to drive to (0, 0). This fixes it and adds test coverage.
=> Fix Trajectory.State not copying all fields correctly

pathplannerlib/src/main/java/com/pathplanner/lib/path/PathPlannerPath.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/path/PathPlannerPath.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/path/PathPlannerPath.h, pathplannerlib/src/test/java/com/pathplanner/lib/path/PathPlannerPathTest.java, pathplannerlib/src/test/native/cpp/pathplanner/lib/path/PathPlannerPathTest.cpp
Similar to #423 . In a localization-less environment it is handy to know the starting pose for swerve paths. This uses the preview state heading, if it is set so you can reset your pose and drive exactly what you see in the gui.
=> Expose holomonic preview path in PathPlannerPath

pathplannerlib/src/main/java/com/pathplanner/lib/pathfinding/LocalADStar.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/pathfinding/LocalADStar.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/pathfinding/LocalADStar.h
Now typically runs ~50ms for the first path iteration on a RIO 1. The first run will still take up to 500ms in Java if it is the first piece of PathPlannerLib run since it needs to warm up. But, who does that anyways?
=> Significantly improve pathfinding performance on RIO

pathplannerlib/.vscode/settings.json, pathplannerlib/src/main/java/com/pathplanner/lib/pathfinding/RemoteADStar.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/pathfinding/LocalADStar.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/pathfinding/RemoteADStar.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/pathfinding/RemoteADStar.h, pathplannerlib/src/main/native/include/pathplanner/lib/util/PPLibTelemetry.h
Works with the coprocessor pathfinding binary https://github.com/mjansen4857/pplib_coprocessor
=> RemoteADStar pathfinder implementation

pathplannerlib/src/main/native/include/pathplanner/lib/controllers/PPHolonomicDriveController.h
We are currently using PathPlanner for our robot, we are testing the code using a Gazebo simulation. The simulated robot didn't seem to turn at all, while the real robot did it without issue. We looked into it and found that the m_enabled check in PPHolonomicDriveController was failing, we believe it is because the variable is not assigned anything, leaving the compiler to decide its value. On Java the variable is set to true when its declared.
=> Initialize m_enabled to true in PPHolonomicDriveController

pathplannerlib-python/pathplannerlib/commands.py, pathplannerlib/src/main/java/com/pathplanner/lib/commands/PathfindingCommand.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/PathfindingCommand.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/commands/PathfindingCommand.h, pathplannerlib/src/main/native/include/pathplanner/lib/controllers/PPHolonomicDriveController.h
We are currently linking a Pathfind and Follow Path command to a button on our robot. We got it working great for the blue side of the field, but on the red side the Pathfinding would target the wrong angle. Once the actual follow path command started the heading got corrected properly. It seems like the heading issue was caused because m_goalEndState was not updated after m_targetPose was flipped. 
Regarding the idempotency issue, we noticed that using the command several times caused the heading to flip each time PathfindingCommand::Initialize was run, we just added a check so its only flipped once.
=> Fix idempotency and flipping issue with PathfindingCommand

pathplannerlib-python/pathplannerlib/auto.py, pathplannerlib/src/main/java/com/pathplanner/lib/auto/NamedCommands.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/NamedCommands.cpp
My kids had a capitalization problem with a named command and didn't know why their thing wasn't getting scheduled. By at least logging a warning, there is some insight to what is going wrong.
Alternatively, you can hard fail with an exception. I think it is bad that there can be a discrepancy that silently fails between what you see in the gui and what gets run on the robot.
=> Add driver station warning if named command is not known

pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/FollowPathCommand.cpp
The latest updates that changed event markers to be time based caused paths with events to crash on C++.  
When doing:
```
m_untriggeredEvents.insert(m_untriggeredEvents.end(),
m_generatedTrajectory.getEventCommands().begin(),
m_generatedTrajectory.getEventCommands().end());
```
A new vector is created each time m_generatedTrajectory.getEventCommands() is called, meaning that the iterators are not linked. I solved this by storing the eventCommands in a different variable and then getting the begin and end iterators from it. Another solution could maybe be changing PathPlannerTrajectory::getEventCommands to return a constant reference to the events.
=> Fix paths with events on C++

Writerside/topics/pplib-Pathfinding.md
A `frc2::CommandPtr` does not have a `.ToPtr()` function, and it's not needed, as it's already a pointer.
=> Remove .ToPtr() from the C++ examples for pathfinding

Writerside/topics/pplib-Build-an-Auto.md, pathplannerlib-python/pathplannerlib/auto.py
Was already doing this for my team's robotpy code so I figured why not implement it here. As far as my testing extends, it works, I am not 100% sure if I implemented the docs correctly, however.
=> Implemented buildAutoChooser() in Python.

Writerside/cfg/buildprofiles.xml, Writerside/topics/pplib-Build-an-Auto.md
=> Show a warning regarding loading autos when code starts

lib/widgets/editor/tree_widgets/commands/command_group_widget.dart, lib/widgets/editor/tree_widgets/commands/duplicate_command_button.dart, lib/widgets/editor/tree_widgets/commands/named_command_widget.dart, lib/widgets/editor/tree_widgets/commands/path_command_widget.dart, lib/widgets/editor/tree_widgets/commands/wait_command_widget.dart
Create a button on the PathPlanner GUI to duplicate an action (a path, command, command group).
Implementation of https://github.com/mjansen4857/pathplanner/issues/652
=> Add a duplicate/copy button for each action in the autos on the PathPlanner client

Writerside/topics/pplib-Build-an-Auto.md, pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/AutoBuilder.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/auto/AutoBuilder.h
Added a equivalent version of buildAutoChooser for cpp from java.
Using the std::filesystem, we can inspect the files on the drive.
Since SendableChooser doesn't allow for rvalue storage, we need to store the commands ourselves so the user will not get a nullptr when trying to access a command* from GetSelected().
=> Added buildAutoChooser to C++ lib

Writerside/topics/pplib-Build-an-Auto.md, pathplannerlib/src/main/java/com/pathplanner/lib/auto/AutoBuilder.java
I created a new method called `buildAutoChooserWithOptionsModifier`, that accepts a second parameter in the form of a lambda function that takes in a stream and returns a stream of PathPlannerAutos.
I also added documentation to filter these options based on if they included the text "comp" at the beginning of the name. Some other examples you could do would be override the name with `.setName`, filter depending on if you're red or blue, or use [`.sorted()`](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#sorted--) on the stream to sort them arbitrarily before going on shuffle board.
I couldn't run spotless for some weird errors in my environment I need to figure out but the formatting should be good enough. I also manually wrote that documentation so no guarantees …
=> Add buildAutoChooserWithOptionsModifier 

.github/workflows/publish-docs.yml, Writerside/topics/pplib-Build-an-Auto.md, pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/AutoBuilder.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/auto/AutoBuilder.h
SendableChooser references a map of all of the auto commands 
Filter provides access to auto command (const) and auto's path
Allows multiple SendableChooser
Allows commands to be updated to latest in pathplanner/auto directory (regenerateSendableReferences()) 
Provided wiki info for filtering
=> Added filtering for buildAutoSendable()

Writerside/topics/pplib-Build-an-Auto.md, pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/AutoBuilder.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/auto/AutoBuilder.h
Changed filtering function from `const PathPlannerAuto* const`-> `const PathPlannerAuto&`: Easier syntax, reference act like varible instead of pointer
`const_cast<>` can still change the const-ness of `PathPlannerAuto&` which allows them to edit directly (I despise this feature, however there is no copy constructor for `PathPlannerAuto` due to `unique_ptr`)
Replace `dynamic_cast<>` to `static_cast<>` since we know relationship at compile time 
Set `filter` as first parameter and `defaultAutoName` as second (which is defaulted), which prevents confusion as to why there is an empty string input (in user code)
Separated `buildAutoChooser` into `buildAutoChooser`, `buildAutoChooserFilter`, and `buildAutoChooserFilterPath` for different degrees of concern and to mirror java version more …
=> Style changes to buildAutoChooser

examples/cpp/src/main/cpp/subsystems/SwerveSubsystem.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/AutoBuilder.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/FollowPathCommand.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/PathfindingCommand.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/util/PathPlannerLogging.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/auto/AutoBuilder.h, pathplannerlib/src/main/native/include/pathplanner/lib/commands/FollowPathCommand.h, pathplannerlib/src/main/native/include/pathplanner/lib/commands/PathfindThenFollowPath.h, pathplannerlib/src/main/native/include/pathplanner/lib/commands/PathfindingCommand.h, pathplannerlib/src/main/native/include/pathplanner/lib/path/PathPlannerPath.h, pathplannerlib/src/main/native/include/pathplanner/lib/util/PathPlannerLogging.h
The C++ `AutoBuilder` lambdas can take const references instead of values. WPILib typically passes `Pose2d` and `ChassisSpeeds` by const reference, and the `DriveFeedforwards` type contains vectors that shouldn't be copied on every call to `output`.
=> Switch C++ AutoBuilder `std::function`s to accept `const&`

Writerside/topics/pplib-Build-an-Auto.md
The Autobuilder example in the [documentation](https://pathplanner.dev/pplib-getting-started.html#install-pathplannerlib) did not match the [project example](https://github.com/mjansen4857/pathplanner/blob/main/examples/cpp/src/main/cpp/subsystems/SwerveSubsystem.cpp) for C++.
=> Make documentation Autobuilder example match the project example for C++

pathplannerlib-python/pathplannerlib/util.py, pathplannerlib/src/main/java/com/pathplanner/lib/util/DriveFeedforwards.java, pathplannerlib/src/main/java/com/pathplanner/lib/util/FlippingUtil.java, pathplannerlib/src/main/native/include/pathplanner/lib/util/DriveFeedforwards.h, pathplannerlib/src/main/native/include/pathplanner/lib/util/FlippingUtil.h
1. The robot-relative feedforward Y components need to be inverted in `kMirrored` mode, as left and right are flipped.
2. In `kRotational` mode, the field rotation needs to be rotated by 180 degrees, not subtracted from 180 degrees. For example, a 90 degree rotation should become -90 after rotating, but stay 90 degrees after mirroring.
I wasn't sure what the best way to implement 1 is API-wise, so for now I implemented two new functions `flipFeedforwardXs` and `flipFeedforwardYs` to handle the two components. Feel free to rename the functions or try to merge them into the existing `flipFeedforwards` function
=> Fix `FlippingUtil` behavior with `kMirrored` robot-relative forces and `kRotational` field rotation

pathplannerlib-python/pathplannerlib/trajectory.py, pathplannerlib/src/main/java/com/pathplanner/lib/trajectory/PathPlannerTrajectory.java, pathplannerlib/src/main/java/com/pathplanner/lib/util/swerve/SwerveSetpointGenerator.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/trajectory/PathPlannerTrajectory.cpp
Add an angle check to prevent the following from being printed continuously (may need to be added on some other `getAngle()` as well. 
```
Error at java.base/java.lang.Thread.getStackTrace(Thread.java:1619): x and y components of Rotation2d are zero
at java.base/java.lang.Thread.getStackTrace(Thread.java:1619)
at edu.wpi.first.math.geometry.Rotation2d.<init>(Rotation2d.java:122)
at edu.wpi.first.math.geometry.Translation2d.getAngle(Translation2d.java:174)
at com.pathplanner.lib.util.swerve.SwerveSetpointGenerator.generateSetpoint(SwerveSetpointGenerator.java:345)
....
at com.ctre.phoenix6.swerve.SwerveDrivetrain.setControl(SwerveDrivetrain.java:413)
at frc.robot.subsystems.drivetrain.CommandSwerveDrivetrain.lambda$14(CommandSwerveDrivetrain.java:266)
at …
```
=> Angle check

Writerside/topics/pplib-Build-an-Auto.md, examples/cpp/build.gradle, examples/java/build.gradle
https://docs.wpilib.org/en/latest/docs/software/advanced-gradlerio/compiler-args.html#deleting-unused-deploy-files
=> Use deleteOldFiles = true

pathplannerlib/src/main/java/com/pathplanner/lib/util/swerve/SwerveSetpointGenerator.java
This prevents Rotation2d from screaming in the console from both x and y being 0 when the module isn't applying a force.
=> [Swerve Setpoint Generator] Prevent force from being applied to chassisTorque if the magnitude of the force is 0

pathplannerlib-python/pathplannerlib/util/swerve.py, pathplannerlib/src/main/java/com/pathplanner/lib/util/swerve/SwerveSetpointGenerator.java
Adds an option to generate a SwerveSetpoint with a specified battery voltage instead of depending on RobotController.getInputVoltage(). 
Additionally, by default checks if RobotController.getInputVoltage() is returning NaN and if it is, uses 12.0 as a sub in voltage.
=> Update SwerveSetpointGenerator to handle NaN Voltages

pathplannerlib-python/pathplannerlib/util/swerve.py, pathplannerlib/src/main/java/com/pathplanner/lib/util/swerve/SwerveSetpointGenerator.java
This replaces the iterative root finder in SwerveSetpoint generator, used for `findDriveMaxS` and `findSteeringMaxS`, with direct solutions for each of them. 
This is currently a draft because:
- I derived these about 6 months ago so I don't remember the exact details, I will try to re-derive them and add explanations later.
- It is currently untested as I am writing this on a Chromebook.
=> Replace iterative solver in SwerveSetpointGenerator with direct solutions

pathplannerlib-python/pathplannerlib/util/swerve.py, pathplannerlib/src/main/java/com/pathplanner/lib/util/swerve/SwerveSetpointGenerator.java
This prevents an extremely rare but still possible warning from Rotation2d about x and y being 0, as Rotation2d uses 1e-6 as its epsilon for 0 checking.
=> [Swerve Setpoint Generator] Raise kEpsilon from 1e-8 to 1e-6

Writerside/topics/pplib-Swerve-Setpoint-Generator.md, pathplannerlib/src/main/native/cpp/pathplanner/lib/config/RobotConfig.cpp, pathplannerlib/src/main/native/cpp/pathplanner/lib/util/swerve/SwerveSetpointGenerator.cpp, pathplannerlib/src/main/native/include/pathplanner/lib/config/ModuleConfig.h, pathplannerlib/src/main/native/include/pathplanner/lib/config/RobotConfig.h, pathplannerlib/src/main/native/include/pathplanner/lib/util/swerve/SwerveSetpoint.h, pathplannerlib/src/main/native/include/pathplanner/lib/util/swerve/SwerveSetpointGenerator.h
I translated the swervepoint generator to C++, but documentation still needs to be updated but just wanted to create the PR in case there is something wrong with the translation
=> Add Swerve Setpoint Generator to PPLib C++

pathplannerlib/src/main/java/com/pathplanner/lib/config/RobotConfig.java
This pull request adds the ability to check whether hard-coded RobotConfig matches the configuration in GUI.
=> Add Alerts to RobotConfig

pathplannerlib/src/main/java/com/pathplanner/lib/util/FlippingUtil.java
The `vy` for the flipped chassis speeds was accidentally put as `-vx` in the Java version of PPLib
Resolves #988
=> [PPLib] Fix chassis speeds flipping in java

pathplannerlib-python/pathplannerlib/util/swerve.py
I believe this was broken by 2025 WPILib.
=> Fix Python AttributeError in SwerveSetpointGenerator

pathplannerlib-python/pathplannerlib/path.py, pathplannerlib/src/main/java/com/pathplanner/lib/path/IdealStartingState.java
I believe I've fixed the typo.
If there could be more clarification added, I'd be interested. I find the term "Ideal" a bit vague. Does it mean the "expected" starting state? That would make sense to me since I'm using it for on-the-fly generation, but I'm not sure if there are other use cases of the class.
=> Fix typo in IdealStartingState Javadoc (#1007)

lib/trajectory/trajectory.dart, pathplannerlib-python/pathplannerlib/trajectory.py, pathplannerlib/src/main/java/com/pathplanner/lib/trajectory/PathPlannerTrajectory.java, pathplannerlib/src/main/native/cpp/pathplanner/lib/trajectory/PathPlannerTrajectory.cpp
Also attempt to add unit tests to exercise this code, but they are Windows-specific at the moment (needs fix!)
=> Fix oscillating velocity for differential drive

pathplannerlib-python/pathplannerlib/trajectory.py
The title describes the commit. This crash occured because a Translation2d (in line 204 of the trajectory.py file) was being constructed with a float and a Rotation2d and no keyword arguments, which it doesn't like. I just added keyword arguments, which fixes the crash.
This is my first pull request to an actual project, so please forgive any errors :D
=> Fix pathfindToPose crashing with nonzero goal end velocity in Python

Writerside/topics/pplib-Pathfinding.md
Fix C++ Documentation for pathfindThenFollowPath() and pathfindToPose() Angular Acceleration units. Remove Rotation Delay
=> Change C++ angular acceleration units from deg_per_s to deg_per_s_sq
