- README.md
- js/pathplanner.js
- path_generator.js
Some path following algorithms need the x and y coordinates
> Add x and y positions as output format options

- js/path_editor.js
- package-lock.json
Added code to constrain the main point of a spline on the Y-axis if the shift button is held down.
This is similar to constraining the angle of the offset control points of a spline.
Also, my code editor made some cosmetic code formatting changes as well. Sorry.
> Constrain the main point of a spline on the Y-axis if the shift button is held down

- lib/robot_path/robot_path.dart
- lib/widgets/path_editor/path_editor.dart
Good day,
This PR changes the generation of waypoints. New waypoints are added via a double click from the last selected waypoint. This allows new points to be added mid-path, which is very useful for adding changes to the start of a long path.
Best,
Jack
Programming Lead - Texas Torque (FRC 1477)
Closes #56
> Support adding a waypoint in the middle of a path

- lib/pages/home_page.dart
- lib/widgets/drawer_tiles/settings_tile.dart
- lib/widgets/field_image.dart
- lib/widgets/import_field_dialog.dart
- lib/widgets/path_editor/path_editor.dart
- lib/widgets/path_editor/path_painter.dart
- lib/widgets/path_editor/waypoint_card.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
> Custom field images

- lib/robot_path/robot_path.dart
- lib/widgets/path_editor/generator_settings_card.dart
- lib/widgets/path_editor/path_editor.dart
- lib/widgets/path_editor/path_info_card.dart
- lib/widgets/path_editor/waypoint_card.dart
> Movable path editor cards

- lib/robot_path/robot_path.dart
- lib/services/generator/trajectory.dart
- lib/widgets/path_editor/path_painter_util.dart
- pathplannerlib/src/main/java/com/pathplanner/lib/PathPlannerTrajectory.java
- pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlannerTrajectory.cpp
- Add resolution as a constant in Trajectory
- Lerp between trajectory states to find the marker time
Fixes mjansen4857/pathplanner#105
> Improved marker time calculation:

- lib/main.dart
> Set a minimum application size.

- lib/services/generator/trajectory.dart
- lib/widgets/path_editor/cards/graph_settings_card.dart
- lib/widgets/path_editor/cards/marker_card.dart
- lib/widgets/path_editor/editors/graph_editor.dart
- lib/widgets/path_editor/editors/marker_editor.dart
- lib/widgets/path_editor/path_editor.dart
- pubspec.lock
- pubspec.yaml
The trajectory is now graphed using fl_chart. #108
> graph trajectory using fl_chart

- pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlanner.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlannerTrajectory.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/controllers/PPHolonomicDriveController.cpp
- pathplannerlib/src/main/native/include/pathplanner/lib/GeometryUtil.h
- pathplannerlib/src/main/native/include/pathplanner/lib/PathConstraints.h
- pathplannerlib/src/main/native/include/pathplanner/lib/PathPlanner.h
- pathplannerlib/src/main/native/include/pathplanner/lib/PathPlannerTrajectory.h
- pathplannerlib/src/main/native/include/pathplanner/lib/PathPoint.h
- pathplannerlib/src/main/native/include/pathplanner/lib/controllers/PPHolonomicDriveController.h
Includes optimizing movement of vectors, as well as objects into vectors. Also includes most variables becoming const (compiler can optimize these variables), and a few general optimizations. Let me know if there's anything about the previous format that you'd prefer to retain.
> More optimizations for C++

- lib/robot_path/robot_path.dart
- lib/robot_path/stop_event.dart
- lib/robot_path/waypoint.dart
- lib/widgets/path_editor/cards/marker_card.dart
- lib/widgets/path_editor/cards/stop_event_card.dart
- lib/widgets/path_editor/cards/waypoint_card.dart
- lib/widgets/path_editor/editors/marker_editor.dart
- pathplannerlib/src/main/java/com/pathplanner/lib/PathPlanner.java
- pathplannerlib/src/main/java/com/pathplanner/lib/PathPlannerTrajectory.java
- pathplannerlib/src/main/java/com/pathplanner/lib/auto/BaseAutoBuilder.java
- pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlanner.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlannerTrajectory.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/BaseAutoBuilder.cpp
- pathplannerlib/src/main/native/include/pathplanner/lib/PathPlannerTrajectory.h
- pathplannerlib/src/main/native/include/pathplanner/lib/auto/BaseAutoBuilder.h
- test/services/generator/trajectory_test.dart
Includes GUI changes to add events between paths in a group + before and after a path. PPLib AutoBuilder fleshed out to support these changes and build complete autonomous commands.
> Autobuilder v2

- lib/pages/home_page.dart
Adds project specific settings
Creates a file `.pathplanner/settings.json` in the project directory with the following contents:
```json
{
"robotSize": {
"width": 0.75,
"length": 1.0
},
"holonomicMode": false,
"generateJSON": false,
"generateCSV": false,
"pplibClient": true
}
```
> Added project specific settings

- lib/robot_path/stop_event.dart
- pathplannerlib/src/main/java/com/pathplanner/lib/PathPlannerTrajectory.java
- pathplannerlib/src/main/java/com/pathplanner/lib/auto/BaseAutoBuilder.java
- pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlanner.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/BaseAutoBuilder.cpp
- pathplannerlib/src/main/native/include/pathplanner/lib/PathPlannerTrajectory.h
Stop event will execute for at least the configured wait time, event if all event commands have already finished.
> Add minimum wait behavior

- pathplannerlib/src/main/java/com/pathplanner/lib/auto/BaseAutoBuilder.java
- pathplannerlib/src/main/java/com/pathplanner/lib/auto/MecanumAutoBuilder.java
- pathplannerlib/src/main/java/com/pathplanner/lib/auto/RamseteAutoBuilder.java
- pathplannerlib/src/main/java/com/pathplanner/lib/auto/SwerveAutoBuilder.java
- pathplannerlib/src/main/java/com/pathplanner/lib/commands/FollowPathWithEvents.java
> Replace HashMap with Map interface

- pathplannerlib/publish.gradle
- pathplannerlib/src/main/java/com/pathplanner/lib/PathPlanner.java
- pathplannerlib/src/main/java/com/pathplanner/lib/PathPlannerTrajectory.java
- pathplannerlib/src/main/java/com/pathplanner/lib/auto/BaseAutoBuilder.java
- pathplannerlib/src/main/native/include/pathplanner/lib/auto/PIDConstants.h
* Replace all remaining usages of ArrayList in Java methods with List
* Make cpp PIDConstants class constexpr
> Minor PPLib changes

- pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/FollowPathWithEvents.cpp
> Fix C++ command requirements are not calculated correctly #244

- pathplannerlib/src/main/native/cpp/pathplanner/lib/PathPlanner.cpp
- pathplannerlib/src/main/native/include/pathplanner/lib/PathPlanner.h
- pathplannerlib/src/main/native/include/pathplanner/lib/PathPlannerTrajectory.h
This basically just implements Pull #270 into C++ as well as publicizing the extra constructor for `PathPlannerTrajectory`. As is it's borderline impossible to create a trajectory tweaked from another trajectory (such as for custom origin flipping).
> Publicize more C++ things

- lib/pages/home_page.dart
Closes #267 and maybe #288 
Also seems to fix not being able to add markers at least for me.
> Markers update

- lib/widgets/editor/split_path_editor.dart
also adjust snapping distance to 0.1m
> negate editor snapping if ctrl held

- lib/services/update_checker.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
> match default gui and pplib versions

- pathplannerlib-python/pathplannerlib/trajectory.py
> make trajectory State class compatible with Python 3.11+

- lib/pages/home_page.dart
- lib/pages/project/project_page.dart
- lib/path/choreo_path.dart
- lib/util/prefs.dart
- test/pages/auto_editor_page_test.dart
- test/pages/project/project_page_test.dart
- test/widgets/editor/split_auto_editor_test.dart
- test/widgets/editor/split_choreo_path_editor_test.dart
- test/widgets/mini_path_preview_test.dart
Updates Choreo interop to work automatically with Choreo's upcoming autosave feature
> Automatic Choreo interop

- pathplannerlib-python/pathplannerlib/commands.py
- pathplannerlib-python/pathplannerlib/pathfinders.py
- pathplannerlib/src/main/java/com/pathplanner/lib/pathfinding/LocalADStar.java
- pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/PathfindingCommand.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/pathfinding/LocalADStar.cpp
- pathplannerlib/src/main/native/include/pathplanner/lib/pathfinding/LocalADStar.h
> pathfinding changes for other languages

- pathplannerlib-python/pathplannerlib/trajectory.py
> remove cyclical import

- pathplannerlib-python/pathplannerlib/commands.py
- pathplannerlib-python/pathplannerlib/path.py
- pathplannerlib-python/pathplannerlib/trajectory.py
- pathplannerlib/src/main/java/com/pathplanner/lib/commands/FollowPathCommand.java
- pathplannerlib/src/main/java/com/pathplanner/lib/commands/PathfindingCommand.java
- pathplannerlib/src/main/java/com/pathplanner/lib/path/IdealStartingState.java
- pathplannerlib/src/main/java/com/pathplanner/lib/path/PathPlannerPath.java
- pathplannerlib/src/main/java/com/pathplanner/lib/path/PathPoint.java
- pathplannerlib/src/main/java/com/pathplanner/lib/trajectory/PathPlannerTrajectory.java
- pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/FollowPathCommand.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/PathfindingCommand.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/path/IdealStartingState.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/path/PathPlannerPath.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/trajectory/PathPlannerTrajectory.cpp
- pathplannerlib/src/main/native/include/pathplanner/lib/commands/FollowPathCommand.h
- pathplannerlib/src/main/native/include/pathplanner/lib/commands/PathfindingCommand.h
- pathplannerlib/src/main/native/include/pathplanner/lib/path/IdealStartingState.h
- pathplannerlib/src/main/native/include/pathplanner/lib/path/PathPlannerPath.h
- pathplannerlib/src/main/native/include/pathplanner/lib/path/PathPoint.h
Helps to reduce the impact of longer generation times due to Trajectory v2
> Pre-generate the ideal trajectory for each GUI path

- lib/pages/home_page.dart
- lib/pages/project/project_page.dart
- lib/util/path_painter_util.dart
- lib/widgets/editor/preview_seekbar.dart
- lib/widgets/editor/tree_widgets/auto_tree.dart
- lib/widgets/editor/tree_widgets/path_tree.dart
- lib/widgets/editor/tree_widgets/reset_odom_tree.dart
- pubspec.lock
- test/pages/project/project_page_test.dart
- test/widgets/editor/preview_seekbar_test.dart
* Update search styling to better match material 3 spec
* Fix robot details being rotated with the robot
* Fix some inconsistent card colors
> some minor fixes

- lib/path/pathplanner_path.dart
- lib/widgets/editor/tree_widgets/path_optimization_tree.dart
> Fix a couple issues

- pathplannerlib/src/main/native/cpp/pathplanner/lib/path/PathPlannerPath.cpp
> Fix loading of choreo paths with splits [C++ pathplannerlib]

- .github/workflows/build-pplib-release.yaml
- .github/workflows/pplib-ci.yml
- pathplannerlib/build.gradle
- pathplannerlib/config.gradle
- pathplannerlib/gradle/wrapper/gradle-wrapper.properties
- pathplannerlib/src/main/java/com/pathplanner/lib/controllers/PPHolonomicDriveController.java
- pathplannerlib/src/main/java/com/pathplanner/lib/path/PathPlannerPath.java
- pathplannerlib/src/main/java/com/pathplanner/lib/trajectory/PathPlannerTrajectory.java
- pathplannerlib/src/main/java/com/pathplanner/lib/util/swerve/SwerveSetpointGenerator.java
This reverts commit 2d72e3da19778301140163c7bbeff906d7be8aeb.
> Revert "Replace usage of deprecated ChassisSpeeds methods (#916)"

- lib/trajectory/trajectory.dart
- lib/util/wpimath/kinematics.dart
- pathplannerlib-python/pathplannerlib/trajectory.py
- pathplannerlib-python/pyproject.toml
- pathplannerlib-python/requirements.txt
- pathplannerlib/src/main/java/com/pathplanner/lib/trajectory/PathPlannerTrajectoryState.java
- pathplannerlib/src/main/native/cpp/pathplanner/lib/trajectory/PathPlannerTrajectoryState.cpp
> Integrate field speeds to interpolate state positions

- lib/pages/home_page.dart
- lib/widgets/field_image.dart
- pubspec.yaml
Also changed the name in the drop-down menu to make it easier to differentiate
> Fix Reefscape annotated field not loading

- pathplannerlib/src/main/native/cpp/pathplanner/lib/events/EventScheduler.cpp
> Use references in EventScheduler for loops

- pathplannerlib/src/main/native/cpp/pathplanner/lib/auto/CommandUtil.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/commands/PathPlannerAuto.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/path/EventMarker.cpp
- pathplannerlib/src/main/native/cpp/pathplanner/lib/path/PathPlannerPath.cpp
- pathplannerlib/src/main/native/include/pathplanner/lib/auto/CommandUtil.h
- pathplannerlib/src/main/native/include/pathplanner/lib/commands/PathPlannerAuto.h
- pathplannerlib/src/main/native/include/pathplanner/lib/path/PathPlannerPath.h
This mirrors the functionality added in #987 for the C++ version of pathplannerlib
> Add path mirroring for C++

- pathplannerlib/src/main/native/include/pathplanner/lib/commands/PathfindThenFollowPath.h
> Fix C++ PathfindThenFollowPath double path flipping issue #1096
